### ISSUE TITLE
You can now use the lamp by clicking on the name of the widget. The shortcut keys have been disabled

### ISSUE THREAD

**Issue by saviourdog** [kauemurakami/getx_snippets_extension#13]
hello,best regrades, wrap with getx...Widget not useful

**Comment by kauemurakami** [comment]
really this is something that bothers me, i will release an update in a few hours with some corrections

**Comment by saviourdog** [comment]
> really this is something that bothers me, i will release an update in a few hours with some corrections

thanks a lot

**Comment by kauemurakami** [comment]
Done 🚀

**Comment by saviourdog** [comment]
@kauemurakami hi,after reinstall getx plugin and restart vscode,it still not working,there is sth i am wrong?

**Comment by kauemurakami** [comment]
strange, everything here is normal, check the truth of your vs code with the minimum descent in the description pfv, if not, return it to me and I will investigate further.
@saviourdog

**Comment by TJMusiitwa** [comment]
I would like to re-open this issue as I am facing the exact same issue on the latest VS Code version 1.55.0 and get version 3.16.1.
There really needs to be a fix for this

**Comment by kauemurakami** [comment]
New version avaible.

**Comment by ShellPeng** [comment]
new version have the same issue

**Comment by ScottishRoss** [comment]
I have this issue. Any suggestions?

**Comment by kauemurakami** [comment]
Hi, so far nothing different, downloads keep increasing, I collected some quick feedbacks here from friends and friends at work, I couldn't identify this bug, in compilation time or in the form of feedback from the marketplace.
Since the first suggestion of this issue, the plugin always worked, except for exceptions of this issue.
One last suggestion, which happened to me only in the testing phase is.
Go to your vscode plugins, find the getxsnippets folders, delete all but the latest version, or all and then download again (may have more than one version installed).
Another thing can also be clearing your vs and pc cache.
If that doesn't solve it, come back and let's investigate further.

**Comment by ScottishRoss** [comment]
Thanks for the quick response @kauemurakami. I've tried these suggestions:
- Clearing cache
- Uninstalling the extension (there was only one version installed)
- Reinstalling the extension (same issue).
- Uninstalled Riverpod extensions, just in case there was a conflict, and that didn't solve it.

I'm not sure what else to try. I'll have a bit of a look around to see if other extensions have had similar issues.
